### ISSUE TITLE
Roadmap to 1.13

### ISSUE THREAD

**Issue by olivierlesnicki** [ChrisHonniball/ember-string-helpers#2]
Is ember-string-helpers compatible with Ember 1.13?

**Comment by ChrisHonniball** [comment]
Yes it is! I'm going to be updating all of my addons very soon.

**Comment by olivierlesnicki** [comment]
Nice one @ChrisHonniball

**Comment by tylerturdenpants** [comment]
Builds pass with PR #6.  Issue can be closed.
