### ISSUE TITLE
Shouldn't import moment from bower

### ISSUE THREAD

**Issue by vlascik** [ChrisHonniball/ember-string-helpers#3]
This addon probably shouldn't import moment with bower, as it creates problems (multiple versions of `moment` are imported, `moment-timezone` doesn't work) for people that use npm's `ember-cli-moment-shim`, which is probably how most people include moment these days.
Maybe just add `"ember-cli-moment-shim": "^1.3.0",` to `package.json` instead.

**Comment by tylerturdenpants** [comment]
I have submitted a pull request that should address this: #6
