### ISSUE TITLE
Transfer repo?

### ISSUE THREAD

**Issue by tylerturdenpants** [ChrisHonniball/ember-string-helpers#5]
Are you interested in transferring ownership of this addon?  It hasn't been updated in awhile.  Or are you more interested in PR's?

**Comment by ChrisHonniball** [comment]
I still use it on my production application. Pull requests are great if you want to add something.

**Comment by tylerturdenpants** [comment]
Absolutely.  I use it in production as well. I will submitt PRs.  Thanks.

**Comment by tylerturdenpants** [comment]
closing in favor of #6
